require("./_generator/subpage")(hexo);
require("./_generator/font")(hexo);
require("./_generator/search")(hexo);
require("./_generator/recent")(hexo);
require("./_generator/sitemap")(hexo);
require("./_generator/pwa")(hexo);
require("./_timeline")(hexo);
require("./_helper")(hexo);
require("./_nunjucks")(hexo);